/*
 * Filename: fill_data.sql
 * Description: Fills the 'plants' database with data about plants
 * Author: Maja Kitek
 * Date: 2023-04-28
 */

/* -- SCIENTIFIC CLASSIFICATION -- */
INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum, species)
VALUES (1, 'monsteras', 'arum', 'water plantains and allies', 'monocotyledons', 'vascular plants', 'swiss cheese plant');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (2, 'calatheas', 'arrowroot', 'gingers, bananas and allies', 'monocotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (3, 'radiator plants', 'pepper', 'pepper plants, birthwords and allies', 'dicotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (4, 'lilies', 'lily', 'lilies, supplejacks and allies', 'monocotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (5, 'prickly pear', 'cactuses', 'pinks, cacti and allies', 'dicotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (6, 'tongavines', 'arum', 'water plantains and allies', 'monocotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (7, 'roses', 'rose', 'roses, elms, figs and allies', 'dicotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (8, 'mums', 'daisy', 'asters bellflowers fanflowers and allies', 'dicotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (9, 'west indian jasmine', 'madder', 'gentians, dogbanes, madders and allies', 'dicotyledons', 'vascular plants');

INSERT INTO scientific_classification(classification_id, genus, family, order, class, phylum)
VALUES (10, 'climbing cacti', 'cactuses', 'pinks, cacti and allies', 'dicotyledons', 'vascular plants');

/* -- PLANT CONDITIONS -- */
INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (1, 'Easy to take care of, resistant to almost all pests and diseases. Perfect option for gardeners with brown thumbs.',  '{"partial sun"}', '{10, 11, 12, 13}', '{"sand", "clay", "chalky", "sandy loam", "acidic", "neutral", "alkaline"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (2, '','{"full sun", "partial sun"}', '{11, 12}', '{"loam", "acidic", "alkaline"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (3, 'Easy to take care of, resistant to almost all pests and diseases. Perfect option for gardeners with brown thumbs.', '{"full sun"}', '{10, 11, 12}', '{"sand", "loam", "acidic", "neutral", "alkaline"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (4, 'Not difficult to take care of. With proper care it will grow well in certain environments.', '{"partial sun"}', '{10, 11, 12}', '{"loam", "chalky", "neutral", "alkaline"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (5, '', '{"full sun", "partial sun"}', '{3, 4, 5, 6, 7, 8, 9}', '{"sand", "loam", "clay", "slightly acidic", "neutral"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (6, 'Easy to take care of, resistant to almost all pests and diseases. Perfect option for gardeners with brown thumbs.', '{"full sun"}', '{9, 10, 11, 12}', '{"sand", "loam", "acidic", "neutral", "alkaline"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (7, 'Easy to take care of, resistant to almost all pests and diseases. Perfect option for gardeners with brown thumbs.', '{"full shade"}', '{10, 11, 12, 13}', '{"loam", "chalky", "clay", "sand", "sandy loam", "acidic", "neutral", "alkaline"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (8, 'Easy to take care of, resistant to almost all pests and diseases. Perfect option for gardeners with brown thumbs.', '{"full sun"}', '{5, 6, 7, 8, 9, 10, 11}', '{"sand", "loam", "clay", "slightly acidic", "neutral", "slightly alkaline"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (9, 'Easy as long as you can give them what they need. They are sensitive to certain types of pests and diseases.', '{"full sun"}', '{5, 6, 7, 8, 9, 10}', '');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (10, 'Easy to take care of, resistant to almost all pests and diseases. Perfect option for gardeners with brown thumbs.', '{"full sun", "partial sun"}', '{9, 10, 11}', '{"acidic", "neutral"}');

INSERT INTO plant_conditions(conditions_id, difficulty_rating, sunlight, hardiness_zone, soil)
VALUES (11, 'Easy as long as you can give them what they need. They are sensitive to certain types of pests and diseases.', '{"partial sun", "full sun"}', '{10, 11, 12}', '{"sand", "loam", "chalky", "acidic", "neutral", "alkaline"}');

/* -- PLANT CHARACTERISTICS -- */
INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (1, '{"herb", "vine"}', '{"perennial"}', '{"spring", "summer"}', 20, 6, 30, 'forests', '{"white", "cream"}', '{"green", "white"}', '"green", "cream", "yellow", "gold", "white", "tan"', '{"green"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (2, '{}', '{"perennial"}', '{"summer"}', 40, , , '', '{"white", "purple"}', '{"green", "purple", "white", "gray", "silver"}', '{}', '{"green", "gray", "silver", "purple"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (3, '{"succulent", "herb"}', '{"perennial"}', '{"spring", "summer"}', 30, 25, 2.5, 'tropical forests', '{"green", "yellow"}', '{"green"}', '{}', '{"green"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (4, '{"herb"}', '{"perennial"}', '{"summer"}', 100, 50, 2.5, 'garden', '{"white", "purple"}', '{"green", "purple"}', '{}', '{"green", "purple", "white"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (5, '{"herb"}', '{"perennial"}', '{"summer"}', 120, 30, 15.0, 'scrub, amongst bracken and on rocky slopes', '{"white", "yellow", "orange"}', '{"green"}', '{"green"}', '{"green"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (6, '{"succulent", "shrub"}', '{"perennial"}', '{"summer"}', 100, 60, 5, 'desert hills, uplands', '{"yellow"}', '{"green"}', '{"red", "purple", "burgundy", "lavender"}', '{"green", "white"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (7, '{"vine", "herb"}', '{"perennial"}', '{}', 2000, 30, 2.5, 'tropical forests', '{"green"}', '{"green", "yellow", "white", "variegated"}', '{"red", "orange", "burgundy"}', '{"green", "yellow", "cream"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color, leaf_color, fruit_color, stem_color)
VALUES (8, '{"shrub", "vine"}', '{"perennial"}', '{"spring", "summer", "fall"}', 200, 183, 5, 'garden', '{"purple", "red", "white", "yellow", "pink", "cream", "orange", "gold"}', '{"green"}', '{"red", "orange"}', '{"green", "brown"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color,  leaf_color, fruit_color, stem_color)
VALUES (9, '{"herb"}', '{"perennial", "annual"}', '{"fall"}', 90, 60, 4, 'cultivated beds', '{"white", "yellow", "purple", "red", "pink", "green", "cream", "orange", "gold}', '{"green"}', '{}', '{"green"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color,  leaf_color, fruit_color, stem_color)
VALUES (10, '{"shrub"}', '{"perennial", "annual"}', '{"spring", "summer", "fall"}', 500, 0, 3, 'river banks, thickets, sparse forests', '{"orange", "red"}', '{"green"}', '{}', '{"green"}');

INSERT INTO plant_characteristics(characteristics_id, plant_type, life_span, bloom_time, plant_height, spread, flower_size, habitat, flower_color,  leaf_color, fruit_color, stem_color)
VALUES (11, '{"succulent", "shrub"}', '{"perennial"}', '{"spring", "summer", "fall"}', 600, 120, 17, 'tropical moist forest', '{"white", "yellow", "pink"}', '{"green"}', '{"pink"}', '{"green", "white"}');

/* -- CARE GUIDE -- */
INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (1, 'It is important to avoid overwatering because the plant is succeptible to root rot. The plant should be watered after the top few inches of the potting soil have been allowed to dry out from the previous watering. The species will grow well if it is watered in a well draining pot.', 'It grows best if it is provided with a balanced fertilizer containing nitrogen phosporus and potassium. Diluted liquid fertilizer or organic granular fertilizer will work for fertilizing this species. For new plants, it is recomennded to fertilize every eight weeks for the first year, then decrease the number in successive years.', 'Trim the dead, diseased, overgrown branches in winter.', '{"spring", "summer", "fall"}', '{"fall", "winter"}', '{"cutting", "layering", "sowing"}', 'Needs excellent drainage in pots.');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (2, '', 'Water calathea monthly, or every 3-4 weeks, with a half-strength balanced fertilizer or a liquid organic fertilizer, such as seaweed or compost tea. This is not necessary during the winter when the plant is in its dormant season.', '', '{}', '{}', '{"division"}', '');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (3, "Pincushion peperomia likes moist soil and can be sensitive to over-watering, which can lead to rot. Under-watering leads to wilting. Potted Pincushion peperomia needs to be watered regularly during the growth season. Allow the soil to dry before watering. During the winter, water occasionally.", "Use a diluted liquid fertilizer bi-weekly for pincushion peperomia during spring. In the summer, you need only apply the solution once a month. It is not necessary to apply any fertilizer during the autumn or winter.", "Trim the diseased, withered leaves once a month.", '{"spring", "fall"}', '{}', '{"cutting"}', 'Flower pots.');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (4, 'Zebra plant loves moisture and hates soaking wet feet, so frequent, even waterings are the best for your plant. When the top of the soil feels dry, thoroughly water your Zebra plant and allow the substrate to drain. It will likely need more frequent water during the growing season.', 'Zebra plant likes fertile soil, so frequent applications of fertilizer are recommended for this plant. Starting in spring and ending late summer, give your plant a balanced liquid fertilizer at 1/4 strength once every 2-4 weeks, depending on the quality of the soil. Be sure not to overfertilize, though!', 'Trim the diseased, withered leaves once a month.', '{"spring", "fall"}', '{}', '{"division"}', 'It is recommended to repot once every 1-2 years.');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (5, "The Orange lily should be watered only when the top layer of soil feels dry to the touch. The most effective method for determining this is to stick a finger tip into the soil to feel whether it's dry or still moist. If the soil is dry, it is time to water again.", "The orange lily should be fertilized with a slow-release fertilizer on the top layer of soil. This species is considered a heavy feeder and will benefit from the addition of fertilizer to the soil. A commercial, slow-release fertilizer with a 14-14-14 nitrogen, phosphorous, and potassium formulation is sufficient. The plant should be fertilized at the time of planting, and then once monthly during the active spring and fall growing season.", '', '{}', '{"summer", "fall"}', '{"division", "sowing"}', '');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (6, "Water Angel's-wings once every two to three weeks, letting the soil dry out between waterings. During its first season, however, keep the soil slightly moist to help the root system establish well. Stop watering entirely during winter.", "Fertilize angel's-wings once monthly with a balanced (such as 20-20-20) or low-nitrogen plant food. Stop fertilizer in late fall, and resume in early spring.", 'Shape the plant every 2 months during the growing season.', '{"spring"}', '{"spring", "summer", "winter"}', '{"cutting", "sowing"}', 'Needs excellent drainage in pots.');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (7, "Golden pothos grows best in moist soil with medium humidity. When growing golden pothos, it is beneficial to mist the plant's leaves regularly with a spray bottle to maintain humidity around the leaf area. The top layer of soil should be allowed to dry between waterings, and the plant will grow best if it is kept in a pot with a draining hole in the bottom.", "Golden pothos requires fertilization for optimal growth. A water soluble fertilizer diluted by half is ideal for fertilizing this species. Between the spring and fall, golden pothos should be fertilized every couple of weeks. In the winter, fertilization can occur monthly. If the plant's leaves turn yellow, it is a sign that more fertilization is necessary.", 'Shape the plant every 2 months during the growing season.', '{"spring", "summer", "fall", "winter"}', '{}', '{"cutting", "layering"}', "Repot in the spring, choosing a container that's no more than 5 cm larger than the plant's rootball. Use a nutrient-rich, soil-based potting mix.");

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (8, "China rose is a very drought-tolerant type of rose but it still benefits from frequent watering during its flowering time. Water the lower section of the plant and the soil around it, without wetting the leaves, if possible. For roses planted in the ground, water until the area seems waterlogged and a small puddle forms around the stems. Water again when the top layer of soil feels dry.", "Fertilize your china rose with a balanced liquid fertilizer every two weeks during the growing period. Dilute the fertilizer into the water that you use for normal watering. You can also apply manure or garden compost in spring, during planting. Roses planted in containers or pots should be fertilized more often than those planted in the ground.", 'Trim the dead, diseased, overgrown branches in winter.', '{"spring", "fall"}', '{"fall"}', '{"cutting", "grafting", "sowing"}', "Increase pot diameter year by year, and replace pots before or after the winter each year. Masonry pots are preferred for potting.");

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (9, "The Florist's daisy should be watered to the extent that their soil is kept evenly moist at all times. When planted in a pot, it must be watered often and kept in a well-draining pot. Watering once or twice a week is sufficient for this species during the active growing period between spring and fall.", "The florist's daisy does not need to be fertilized in order to grow efficiently. If fertilization is preferred, a well-balanced, liquid houseplant fertilizer should be applied during waterings", 'Trim the diseased, withered leaves once a month.', '{"spring"}', '{"fall"}', '{"cutting", "sowing"}', 'Needs excellent drainage in pots.');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (10, 'Average water needs, watering when the top 3 cm of soil has dried out.', 'Fertilization once every 2-3 months during the growing season.', '', '{"spring", "summer"}', '{}', '{"cutting", "layering"}', 'Potted plants should be repotted every 1-2 years.');

INSERT INTO care_guide(care_guide_id, water, fertilization, pruning, planting_time, harvest_time, propagation, potting_suggestions)
VALUES (11, 'During the growing season, water your Queen of the night whenever the surface of the soil dries out, making sure that the soil drains properly afterward. In winter, cut back watering by at least half.', "Apply a dose of diluted 20-20-20 liquid fertilizer to your queen of the night plant's soil every month from spring through fall. A lower-nitrogen fertilizer may also work well, as this plant is sensitive to nitrogen and may grow leggy stems and fewer blooms when over-fertilized.", 'Shape the plant every 2 months during the growing season.', '{"spring", "fall"}', '{"winter", "spring}', '{"cutting", "grafting", "sowing"}', '');

/* -- BASIC PLANT INFO -- */
INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (1, 'monstera deliciosa', '{"tarovine", "fruit salad plant", "ceriman", "mexican breadfruit"}', 'swiss cheese plant', "The swiss cheese plant (Monstera deliciosa) produces bright, glossy leaves and makes a popular houseplant. It is originally native to tropical forest regions in Central America. The nickname swiss cheese plant refers to the small holes that develop in the plant's leaves. The long fruits resemble corncobs and smell sweet and fragrant when ripe.", true, {"Swiss cheese plant - This plant has always been loved for its unique leaves. During the seedling stage, its leaves are intact as a whole. However, as it ages, the leaves begin to pop out holes and lobes. The older it gets, the larger the holes and the larger the leaves are. This makes its leaves very similar looking to the holes in cheese, so it will be called Swiss cheese plant."}, '{"Its leaves are evergreen and extremly shade-tolerant. It is a famous indoor foliage plant. It is commonly used as potted ornamentals in Europe, America and Japan to decorate living rooms and windowsills."}', "Health, longevity, respect for one's elders", 1, 1, 1, 1);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (2, 'goeppertia picturata', '{"variegated prayer plant"}', 'calathea', "Calathea picturata is a species of plant in the family Marantaceae, native to northwest Brazil. It is a clump-forming evergreen perennial growing to 35 to 40 cm. The leaves are dark green above, purple below, marked heavily with silver along the veins and midriff. It is tender, with a minimum temperature of 16 ℃ required, and in temperate areas is cultivated indoors as a houseplant. Under the synonym Goeppertia picturata the cultivar 'Argentea', with silver leaves edged in green, has gained the Royal Horticultural Society's Award of Garden Merit. ", false, '{}', '{}', '', 2, 2, 2, 2);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (3, 'peperomia ferreyrae', '{"happy bean"}', 'pincushion peperomia', "Pincushion peperomia (Peperomia ferreyrae) is a perennial semi-succulent native to rainforests of South America. Pincushion peperomia is also commonly known as Happy Beans Peperomia and Green Beans Peperomia. This species is often grown as a houseplant and should be placed in bright indirect sunlight for optimal growth. Pincushion peperomia slightly moist soil, but is also very vulnerable to overwatering.", false, '{"Pincushion peperomia - The genus name Peperomia means name Pepper-like in Latin. That refers to the pepper-like shape of flowers of these plants. The first part of the common name, pincushion, refers to elongated, densely-packed pointy leaves, which makes it stand out from other species of the genus."}', '{"Despite the fact that the entire genus is named after hte flowers, peperomia ferreyraes clusters of small yellow flowers are not valued. Instead, the plant is cherished for its unique foliage. The small size and lack of tendency to spread makes it ideal for small spaces and arrangement - windowsills, dish gardens, desktops conservatories and greenhouses.}', 'Friendship and devotion', 3, 3, 3, 3);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (4, 'goeppertia zebrina', '{}', 'zebra plant', "zebra plant (goeppertia zebrina) is an evergreen perennial that will grow from 61 to 91 cm tall, with light green leaves accented by dark green stripes. It blooms in summer with purple or white flowers. Prefers partial sun to full shade. Propagate this plant by dividing it every 2 to 3 years. Requires excellent drainage and high humidity. Grows best in indoor gardens and large terrariums.", false, '{"Zebra plant - The emerald green leaves of Goeppertia zebrina are covered in dark green stripes that look like the stripes of a zebra. Therefore, Goeppertia zebrina got its common name zebra plant. The specific epithet "zebrina" in its botanical name means "of zebra" and it refers to its variegated leaves.}', '{"The zebra plant leaf surface is velvety, and is dark green with yellow-green stripes. The back of tender young leaves are light grey-green and the back of old leaves are lilac-red.}', 'Good luck and happiness.', 4, 2, 4, 4);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (5, 'lilium bulbiferum', '{"jimmys bane", "fire lily", "tiger lily"}', 'orange lily', "Orange lily (Lilium bulbiferum) is a flowering herbaceous lily species native to Europe. This species is toxic to cats. Its scientific name means bearing bulbs. Orange lily is the symbol of the Orange Order, a protestant fraternal order in Ireland.", true, '{}', '{"Flowers often symbolize certain emotions and meanings. The orange lily is a symbol of confidence, pride and even wealth. Giving the orange lily as a gift is the perfect sentiment for someone getting a job promotion or a recent graduate. Lilies have been symbolic in many cultures, even in ancient Greek mythology.}', 'It is generally thought of to represent emotions such as confidence and at the extreme, pride.', 5, 4, 5, 5);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (6, 'opuntia microdasys', '{"bunny-ear prickly-pear", "cinnamon cactus", "bunny ears", "polka dot cactus", "bunny ears cactus", "bunny cactus"}', "angel's wings", "Angel's-wings (*Opuntia microdasys*) is a flowering cactus species native to Mexico. Angel's-wings is closely related to Opuntia RFID, which can be differentiated from Opuntia microdasys by its reddish color. Some scientists consider the two cacti to be the same species. This species is also known as the bunny ears cactus, the bunny cactus, or the polka-dot cactus. It is sometimes planted as an ornamental on borders and in gardens.", false, '{"Bunny ears cactus - It has become a popular houseplant because it is easy to take care of the plant and it has a cute appearance with great blooms. However, yellow flowers appear rarely. Despite this, it is very popular in cultivation because of the comical resemblance to a rabbits head. Therefore, it is called bunny ears cactus.}', '{}', 'Hope.', 6, 5, 6, 6);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (7, 'epipremnum aureum', '{"devils ivy", "taro vine", "ceylon creeper", "ivy arum", "money plant", "hunters robe"}', 'golden pothos', "The golden pothos (Epipremnum aureum) is a popular houseplant that is commonly seen in Australia, Asia, and the West Indies. It goes by many nicknames, including devil's ivy, because it is so hard to kill and can even grow in low light conditions. Golden pothos has poisonous sap, so it should be kept away from pets and children.", true, '{"Golden pothos - Since its green leaves are laced with the color gold, it is called Golden Pothos. Epipremnum aureum has a long and tortuous naming history, and it has been reclassified several times. It was first classified as Pothos aureus. In 1962, scholars discovered that it actually had a blossoming phase. Since then, scholars closely observed and investigated the plants flowers, leaves and growth, and determined its latin name to be Epipremnum aureum.", "Devils ivy - Even if kept in the dark, it can stay green the whole year long, just like the tenacity of the devil. It is also known as devils ivy because it is almost impossible to kill."}', '{"The golden pothos is a popular houseplant, largely due to the way in which it cleans the air. In newly-renovated homes, the golden pothos has been shown to absorb benzene, tricholoethylene and formaldehyde, although you cannot rely on the plant alone to remove all harmful gases from a room. Nevertheless, they have tenacious vitality, and can quickly convert formaldehyde into sugars or amino acids, while decomposing any benzene emitted by photocopiers and printers, making it no surprise that this plant is often seen in homes and offices.}', "Happiness, good fortune, determination to achieve one's goals, wealth.", 7, 6, 7, 7);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (8, 'rosa chinesis', '{"garden rose", "bengal rose", "chinese rose"}', 'china rose', "The china rose (Rosa chinensis) is a Southwest China native. The plant has been cultivated for so long that it has become hard to tell the difference between wild and cultivated varieties. With medium-sized clusters of flowers and a long blooming season, it is easy to see why the china rose was chosen as the basis for many rose hybrids.", false, '{"Garden rose - Rosa chinensis has many horticultural varieties, so it has many common names. Since it is most commonly used in gardens, and is also one of the most common plants found in a garden, its most popular name is the china rose.", "China rose - As per its name, the Rosa chinensis originates from China, and is one of the flowers that represents the country.", "Bengal rose - Bengal rose was also a historically-famous name for the plant, as it was used in Bengal to make dye."}', '{"The china rose has many different colors, each with a different meaning. Red symbolizes love, while pink stands for first love. White represents purity and loyalty and blue expresses affection. People seldom send black roses, because although these have a number of meanings, most of them are negative. So, if you are giving these flowers as a gift, choose a color based on your intentions."}', 'Happiness, longevity, eternal spring.', 8, 7, 8, 8);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (9, 'chrysanthemum x morifolium', '{"hardy garden mum", "chrysanthemum"}', 'florists daisy', "Florist's daisy is a Chinese native that has been cultivated as a medicinal and decorative plant for over 2000 years. Today, it is a gardening and florist favorite all over the world. Chrysanthemum × morifolium is a bushy perennial with dark-green leaves and numerous compact flower heads that come in a wide variety of colors. In English, it is affectionately known as “Mum.”", true, '{"Florists daisy - Chrysanthemum × morifolium is a hybrid chrysanthemum often referred to as florists daisy. The common name probably comes from the fact that florists daisy is an important chrysanthemum in the floral industry. There are more than 100 cultivars released within the species Chrysanthemum × morifolium."}', '{"The crysanthemum is related to the Roman Catholic Pope, having a noble and true meaning. It is generally believed that this flower has a refined and outstanding temperament. The chrysanthemum enjoys a high status in Japan, where it is a part of the crest of the Japanese royal family. It represents longing for beauty, freedom and nature. The Japanese also use chrysanthemum to sweep graves, worship ancestors and also in new year celebrations. Different kinds of chrysanthemums represents divination for love; winter chrysanthemums for parting and yellow ones for being successful. In China, it has the meaning of nobility and longevity; in Europe it means nobility. Take careful consideration of the meaning of the chrysanthemum if you want to give it to someone as a gift, as they are often used to memorialize the deceased.}', 'Purity, nobility and longevity', 9, 8, 9, 9);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (10, 'ixora chinesis', '{}', 'chinese ixora', "Chinese ixora (Ixora chinensis) is a tropical evergreen shrub native to China and thus sometimes called simply Chinese Ixora. The red berries and clusters of bright flowers that bloom nearly year-round make this a popular ornamental plant.", false, '{}', '{"It is said that the Ishtha people in Myanmar have a very romantic and interesting marriage custom. Since ancient times, they have lived near the water. Every family with a daughter would build near their house a floating garden with bamboo and wood, planting chinese ixora on it, and then tie it with ropes. On the daughters wedding day, they would dress her up beautifully, then have her sit in the floating garden, and finally cut off the rope and let it float down the river. Early in the morning, the groom would wait on a downstream shore, ready to welcome the small garden carrying the bride. When the garden boat arrived, the groom would grab the rope and pull it ashore, then lead the nride home for the weding."}', 'Rush to the fore', 10, 9, 10, 10);

INSERT INTO basic_plant_info(plant_id, botanical_name, known_as, species, description, poisonous, name_story, interesting_facts, symbolism, plant_characteristics_id, scientific_classification_id, plant_conditions_id, care_guide_id)
VALUES (11, 'epiphyllum oxypetalum', '{"night-blooming cereus", "lady of the bight", "orchid cactus", "jungle cactus", "princess of the night", "dutchmans pipe cactus"}', 'queen of the night', "Queen of the night is a unique flowering plant. Its flowers are funnel-shaped and have clean white petals and an aromatic scent. Each flower blooms on a single quiet night and fades within hours, making the plant a veritable moonlight beauty.", false, '{"Dutchmans pipe cactus - Epiphyllum oxypetalum is also called Dutchmans Pipe cactus because of its curved tube. It is perhaps the most commonly seen of the Epiphyllum genus. Although it blooms better in smaller pots, it somewhat makes a more attractive houseplant before bloom.", "Nightblooming cereus - It blooms rarely and only at night and the flowers wilt before dawn. Though it is sometimes referred to as a Nightblooming cereus, it is not closely related to any of the species in the tribe Cereeae, such as Selenicereus. It is more commonly known as nightblooming cereus. All Cereus species bloom at night and are terrestrial plants while all Epiphyllum species are usually epiphytic."}', '{"Legend goes that the queen of the night flower was punished by a god and could only bloom for just one moment every year. In order to meet her beloved one who collected morning dew for Buddha every year, she could only choose to bloom at that time. So a years worth of charm was put into her blooming at that one moment, hoping her beloved would notice."}', 'Instant beauty, immortality, luck, prosperity.', 11, 10, 11, 11);